version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    networks:
      - app_network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/ElectroShop

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - '5001:5001'
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    networks:
      - app_network
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://backend:5000

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
      - ./database:/database
    networks:
      - app_network
    command: mongod --bind_ip_all
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongo-seed:
    image: mongo:latest
    volumes:
      - ./database:/database
    networks:
      - app_network
    depends_on:
      mongodb:
        condition: service_healthy
    command: mongorestore --host mongodb --db ElectroShop /database

networks:
  app_network:
    driver: bridge
