version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    networks:
      - app_network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/ElectroShop

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - '5001:5001'
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    networks:
      - app_network
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://backend:5000

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
