name: Node.js CI and Docker Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Set up Node.js 18
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies for both frontend and backend
      - name: Install Backend Dependencies
        working-directory: ./Backend
        run: npm install

      - name: Install Frontend Dependencies
        working-directory: ./Frontend
        run: npm install

      # Run the app (if you still want to do this)
      - name: Start the App
        run: npm run dev

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to DockerHub (or your preferred Docker registry)
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./Frontend # Adjust this path to where your Dockerfile is located
          push: true
          tags: yourdockerhubusername/yourrepositoryname:latest
